# **Recurrent Neural Networks (RNNs):**

Importing the libraries

In [ ]:
# Import all the necessary files!
import os
import tensorflow as tf
import keras
from tensorflow.keras import layers
from tensorflow.keras import Model
from os import getcwd

**We are using the imbd dataset available in the tensorflow library.**

IMDB Movie Reviews dataset. This dataset is commonly used for sentiment analysis, where the goal is to classify movie reviews as either positive or negative

In [1]:
from tensorflow.keras.datasets import imdb

# Load the IMDB dataset with the top 10,000 most frequent words
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)


17464789/17464789 [==============================] - 0s 0us/step


In [2]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Pad sequences to the same length (e.g., 200 words)
train_data = pad_sequences(train_data, maxlen=200)
test_data = pad_sequences(test_data, maxlen=200)


# **1. Using a LSTM model, which is one of the variants of RNN**

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model0 = Sequential()
model0.add(Embedding(10000, 32))  # Embedding layer for word representations
model0.add(LSTM(32))  # LSTM layer
model0.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

model0.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
model0.fit(train_data, train_labels, epochs=50, batch_size=128, validation_split=0.2)


**Accuracy, precision, recall and confusion matrix of Model 0**

In [16]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Predictions on the test set
predictions0 = model0.predict(test_data)
predicted_labels0 = (predictions0 > 0.5).astype(int)

# Calculate metrics
accuracy0 = accuracy_score(test_labels, predicted_labels0)
precision0 = precision_score(test_labels, predicted_labels0)
recall0 = recall_score(test_labels, predicted_labels0)
conf_matrix0 = confusion_matrix(test_labels, predicted_labels0)

print("Accuracy: {:.2%}".format(accuracy0))
print("Precision: {:.2%}".format(precision0))
print("Recall: {:.2%}".format(recall0))
print("Confusion Matrix:\n", conf_matrix0)

782/782 [==============================] - 5s 5ms/step
Accuracy: 84.01%
Precision: 83.63%
Recall: 84.58%
Confusion Matrix:
 [[10430  2070]
 [ 1927 10573]]


# **2. Increasing the layers of the LSTM model to see how it affects the accuracy, precision and recall**

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model1 = Sequential()
model1.add(Embedding(10000, 32, input_length=200))  # Embedding layer for word representations
model1.add(LSTM(64, return_sequences=True))  # First LSTM layer with return_sequences=True to stack LSTM layers
model1.add(LSTM(32))  # Second LSTM layer
model1.add(Dense(32, activation='relu'))  # Dense layer with ReLU activation
model1.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
# model.summary()


In [ ]:
model1.fit(train_data, train_labels, epochs=50, batch_size=128, validation_split=0.2)

**Accuracy, precision, recall and confusion matrix of Model 1**

In [20]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Predictions on the test set
predictions1 = model1.predict(test_data)
predicted_labels1 = (predictions1 > 0.5).astype(int)

# Calculate metrics
accuracy1 = accuracy_score(test_labels, predicted_labels1)
precision1 = precision_score(test_labels, predicted_labels1)
recall1 = recall_score(test_labels, predicted_labels1)
conf_matrix1 = confusion_matrix(test_labels, predicted_labels1)

print("Accuracy: {:.2%}".format(accuracy1))
print("Precision: {:.2%}".format(precision1))
print("Recall: {:.2%}".format(recall1))
print("Confusion Matrix:\n", conf_matrix1)

782/782 [==============================] - 7s 8ms/step
Accuracy: 84.39%
Precision: 84.02%
Recall: 84.93%
Confusion Matrix:
 [[10481  2019]
 [ 1884 10616]]


# **3. Using a GRU model, which is another variant of RNN**

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

model2 = Sequential()
model2.add(Embedding(10000, 32))  # Embedding layer for word representations
model2.add(GRU(32))  # GRU layer
model2.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [ ]:
model2.fit(train_data, train_labels, epochs=50, batch_size=128, validation_split=0.2)


**Accuracy, precision, recall and confusion matrix of Model 2**

In [9]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Predictions on the test set
predictions2 = model2.predict(test_data)
predicted_labels2 = (predictions2 > 0.5).astype(int)

# Calculate metrics
accuracy2 = accuracy_score(test_labels, predicted_labels2)
precision2 = precision_score(test_labels, predicted_labels2)
recall2 = recall_score(test_labels, predicted_labels2)
conf_matrix2 = confusion_matrix(test_labels, predicted_labels2)

print("Accuracy: {:.2%}".format(accuracy2))
print("Precision: {:.2%}".format(precision2))
print("Recall: {:.2%}".format(recall2))
print("Confusion Matrix:\n", conf_matrix2)

782/782 [==============================] - 4s 4ms/step
Accuracy: 83.64%
Precision: 84.26%
Recall: 82.74%
Confusion Matrix:
 [[10568  1932]
 [ 2158 10342]]


# **4. Increasing the layers of the GRU model to see how it affects the accuracy, precision and recall.**

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

model3 = Sequential()
model3.add(Embedding(10000, 32, input_length=200))  # Embedding layer for word representations
model3.add(GRU(64, return_sequences=True))  # First GRU layer with return_sequences=True to stack GRU layers
model3.add(GRU(32))  # Second GRU layer
model3.add(Dense(32, activation='relu'))  # Dense layer with ReLU activation
model3.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

model3.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
# model3.summary()


In [23]:
model3.fit(train_data, train_labels, epochs=50, batch_size=128, validation_split=0.2)


157/157 [==============================] - 3s 19ms/step - loss: 4.2003e-04 - accuracy: 0.9999 - val_loss: 1.3172 - val_accuracy: 0.8578
Epoch 46/50
157/157 [==============================] - 3s 21ms/step - loss: 4.2366e-04 - accuracy: 0.9999 - val_loss: 1.3470 - val_accuracy: 0.8568
Epoch 47/50
157/157 [==============================] - 4s 24ms/step - loss: 3.8350e-04 - accuracy: 0.9999 - val_loss: 1.3657 - val_accuracy: 0.8572
Epoch 48/50
157/157 [==============================] - 3s 20ms/step - loss: 3.6920e-04 - accuracy: 0.9999 - val_loss: 1.3656 - val_accuracy: 0.8572
Epoch 49/50
157/157 [==============================] - 3s 20ms/step - loss: 3.6183e-04 - accuracy: 0.9999 - val_loss: 1.4036 - val_accuracy: 0.8578
Epoch 50/50
157/157 [==============================] - 3s 19ms/step - loss: 3.3780e-04 - accuracy: 0.9999 - val_loss: 1.4333 - val_accuracy: 0.8568


**Accuracy, precision, recall and confusion matrix of Model 3**

In [24]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Predictions on the test set
predictions3 = model3.predict(test_data)
predicted_labels3 = (predictions3 > 0.5).astype(int)

# Calculate metrics
accuracy3 = accuracy_score(test_labels, predicted_labels3)
precision3 = precision_score(test_labels, predicted_labels3)
recall3 = recall_score(test_labels, predicted_labels3)
conf_matrix3 = confusion_matrix(test_labels, predicted_labels3)

print("Accuracy: {:.2%}".format(accuracy3))
print("Precision: {:.2%}".format(precision3))
print("Recall: {:.2%}".format(recall3))
print("Confusion Matrix:\n", conf_matrix3)

782/782 [==============================] - 6s 7ms/step
Accuracy: 84.70%
Precision: 85.00%
Recall: 84.29%
Confusion Matrix:
 [[10640  1860]
 [ 1964 10536]]
